### PR TITLE
fix/2503: break on locked node collision

### LINKED ISSUE #2503: Drag and drop a widget on top of a locked widget
## Subject of the issue
It is possible to drag one item and drop it such that it overlaps with a locked widget.

## Your environment
GridStack 9.3.0
Windows 10
Chrome browser

## Steps to reproduce
Please check out the jsfiddle. There are reproduction steps and grid items to reproduce
https://jsfiddle.net/richsalcedo6/c142owne/

## Expected behavior
I would expect that the drop would not be possible

### PR DESCRIPTION
**Pull request by JakubEleniuk**
### Description
Fixes #2503 

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing (`yarn test`)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

File: src/gridstack-engine.ts [hunk 1]
```diff
@@ -160,28 +160,30 @@ export class GridStackEngine {
 
     let collide: GridStackNode;
     let overMax = 0.5; // need >50%
-    collides.forEach(n => {
-      if (n.locked || !n._rect) return;
+    for (let n of collides) {
+      if (n.locked || !n._rect) {
+        break;
```
Comment (adumesny) [inline src/gridstack-engine.ts:165]: of course, such a simple fix. if any are locked bailed out of the entire loop...
